### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by TechPunk316**
Updating the main page for style. Please also see whether the contact suggestions are appropriate and add the necessary contacts (email/Slack) or remove if they are not required.

### CODE REVIEW

**Comment by jonodrew** [comment]
@bruntonspall what do you think? We could use our team email as a contact, but it will probably increase traffic...

**Comment by bruntonspall** [comment]
I'm content with this as discussed in person. 
I don't think we currently have an email address that is suitable.  The most likely would be to go to the GSG Cyber team, but some of the policies and guidance we put here would need to be directed to GDS or to the Physical or Personnel team, so we probably need a contact address and a triage process.

**Comment by jonodrew** [comment]
I'll check with professions to add the actual number of professionals, and then I think this is ready for merging

**Review by jonodrew — APPROVED** [review]
@TechPunk316 looks good. Can you merge please?

**Pull request merged**
